### ISSUE TITLE
Any plan to provide prompt settings and dataset loaders?

### ISSUE THREAD

**Issue by init0xyz** [wshi83/MedAdapter#1]
Hi, thank you so much for your excellent work!

I noticed that the dataset loader and prompt settings seem to be missing in the `generator/trainer.py` file:
```python
from data.dataset_loader import get_datasets
from utils.util import load_config
from data.prompt_loader import load_prompts
```
Are there any plans to provide these data loaders? Additionally, it seems that the inference code for ChatGPT might be missing from `main-openai.py`. Is it intended to function the same as in `main.py`(i.e., `reward_guide` argument in `main.py`)?

Thank you for your time, and I appreciate any clarification you can provide!

**Comment by wshi83** [comment]
Thank you so much for your comments. We have updated the dataset_loader and prompt_loader.

**Comment by init0xyz** [comment]
Thanks!

**Comment by init0xyz** [comment]
Thanks!
